# Generated by Django 4.2.7 on 2025-10-29 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('iata_code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude_ft', models.IntegerField(blank=True, null=True)),
                ('is_major_hub', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(blank=True, default='', max_length=120)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='maps.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='maps.airport')),
            ],
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['iata_code'], name='maps_airpor_iata_co_b8c680_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['country'], name='maps_airpor_country_3348d6_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['city'], name='maps_airpor_city_67d098_idx'),
        ),
        migrations.AddIndex(
            model_name='flightroute',
            index=models.Index(fields=['airline'], name='maps_flight_airline_c95a48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flightroute',
            unique_together={('origin', 'destination', 'airline')},
        ),
    ]
